### PR TITLE
Fix error display for register and login pages

### PR DESCRIPTION
**Pull request by Akasora39**
Fixed errors to display errors passed from express-validator when provided with insufficient credentials for register and login.

### CODE REVIEW

**Comment by synzen** [comment]
it seems like Github Actions hung up - could you try a random push to see if it triggers it again @Akasora39

**Comment by Akasora39** [comment]
> it seems like Github Actions hung up - could you try a random push to see if it triggers it again @Akasora39
> 
> Edit: forgot I could do it too

Seems like it hung up again on queueing the checks. Not sure what changed from yesterday.

**Comment by Akasora39** [comment]
> > it seems like Github Actions hung up - could you try a random push to see if it triggers it again @Akasora39
> > Edit: forgot I could do it too
> 
> Seems like it hung up again on queueing the checks. Not sure what changed from yesterday.

Aaaaaand it all failed lol

**Comment by synzen** [comment]
> 
> 
> > > it seems like Github Actions hung up - could you try a random push to see if it triggers it again @Akasora39
> > > Edit: forgot I could do it too
> > 
> > 
> > Seems like it hung up again on queueing the checks. Not sure what changed from yesterday.
> 
> Aaaaaand it all failed lol

yeah this one I cancelled cause it hung up again after my commit there lol. if you check the Actions tab on our repo we see all those queued up workflows that are just stuck

**Comment by Akasora39** [comment]
> yeah this one I cancelled cause it hung up again after my commit there lol. if you check the Actions tab on our repo we see all those queued up workflows that are just stuck

Ah I see. Any insights on why this may be taking longer than it normally does?

**Comment by synzen** [comment]
no idea, I think it's completely borked atm lol, pretty sure it doesn't take over 4 hours for it to run

**Pull request merged**
