### PR TITLE
Add item route unit tests, add server scripts

### PR DESCRIPTION
**Pull request by synzen**
- Add item route unit tests
- Organize tests into test dir
- Add separate scripts for unit and integration runs (since int runs are slower)
- Add `lint-fix` script

### CODE REVIEW

**Comment by synzen** [comment]
we can do that - changed accordingly

I was also looking through the tests and found this one https://github.com/CSC59939/QuickBorrow/blob/2e558a68f2d9152b2d7b82aef0452b494da88945/server/database/models/User.int.test.js

i don't believe this would be a relevant integration test because this is testing _mongoose_ and _mongodb_ functions, rather than the function of our own logic (and such functions would already be tested by the mongodb/mongoose teams themselves)

**Comment by Akasora39** [comment]
> we can do that - changed accordingly
> 
> I was also looking through the tests and found this one https://github.com/CSC59939/QuickBorrow/blob/2e558a68f2d9152b2d7b82aef0452b494da88945/server/database/models/User.int.test.js
> 
> i don't believe this would be a relevant integration test because this is testing _mongoose_ and _mongodb_ functions, rather than the function of our own logic (and such functions would already be tested by the mongodb/mongoose teams themselves)

That's true. I suppose the file in question we really want to be testing would be users.js in the routes directory. Also, going off from this, that would mean we wouldn't be testing express-validator for our integration tests.

**Comment by synzen** [comment]
yea, since we're using express-validator in integration tests, i believe we just have to assert that if we send an invalid json body in the request, then the response should have an indication showing what was wrong in the body (basically test the public interface, instead of the internals that is express-validator). we're working under the assumption that express-validator works as intended, and returns the appropriate response (CSC 335 paradigms throwback!)

**Comment by Akasora39** [comment]
> yea, since we're using express-validator in integration tests, i believe we just have to assert that if we send an invalid json body in the request, then the response should have an indication showing what was wrong in the body (basically test the public interface, instead of the internals that is express-validator). we're working under the assumption that express-validator works as intended, and returns the appropriate response (CSC 335 paradigms throwback! if you know what I mean lol)

Lol alright sounds good.

**Pull request merged**
